version: '2'

services:
  sentinel:
    image: docker.io/bitnami/redis-sentinel:6.0-debian-10
    ports:
      - "26379:26379"
    environment:
      - REDIS_MASTER_HOST=redis
  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
